### ISSUE TITLE
Compiled from source, does not work

### ISSUE THREAD

**Issue by PaoloBolzoniBusiness** [cirsfid-unibo/lime#68] opened 2018-04-13 08:55 UTC
I managed to set up a working copy of LIME on my system, now I wanted to try from source. But something goes wrong.

In the system are installed the following relevant programs:
```
abiword 2.8.2
ruby 2.5.1p57
python 2.7.14
sencha cmd 5.1.3.6
npm 5.6.0
node 9.11.1

java
openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-b12)
OpenJDK 64-Bit Server VM (build 25.162-b12, mixed mode)

php7.2.4
```

I downloaded from the repo:
```
lime-server-master.zip
lime_ext_workspace.zip
lime-master.zip
```

To compile I did the following:
I unpack lime-master and lime_ext_workspace in the same directory and basically compiled with the following commands (/src/http is the directory served by the php enable http server):
```
$ sed -i ./packages/ext-theme-lime/sass/etc/customizations.scss -e '1i@charset "UTF-8";'
$ cp -r languagesPlugins php    /srv/http
$ sencha app build
$ cd ./build/production/LIME/
$ cp -r *    /srv/http
```

I unpack lime-server-master.zip and just execute:
```
$ npm install
```

Following the instructions I also pointed the system to the MongoDB and the eXistDB, and everything seems to start properly.

However, when I connect to the website, it does not work. The Chrome DevTools show this error message. Lime pretty much show no relevant log.
```
Uncaught TypeError: Cannot set property 'name' of undefined
    at ag.loadPluginStructure (app.js?_dc=1523609557418:1)
    at ag.load (app.js?_dc=1523609557418:1)
    at ag.constructor (app.js?_dc=1523609557418:1)
    at new ag (app.js?_dc=1523609557418:1)
    at Object.E [as derive] (app.js?_dc=1523609557418:1)
    at app.js?_dc=1523609557418:1
```

**Comment by obujor** [comment] 2018-04-13 09:07
Hi Paolo,
the problem is that downloading lime source as a zip file it doesn't include submodules, you can check this by looking if `langagesPlugins/akoma3.0` folder is empty.
I suggest you to clone the repository with `git clone --recursive` command, in this way git fetches all submodules.
After you have to tun `npm install` command inside `scripts` folder not in the root.
And in the end `sencha app build` in the LIME root.

PS: you don't have to copy _langugesPlugins_ and _php_ folder manually, they're included by sencha build in ` ./build/production/LIME/`.

**Comment by PaoloBolzoniBusiness** [comment] 2018-04-13 12:16
Looks like the problem was indeed the lack of "recursive."

Just to be sure. `npm install` have to be executed on the directory `lime/scripts` *and* in the `lime-server` directory? Or the latter is unneded?

**Comment by PaoloBolzoniBusiness** [comment] 2018-04-13 15:39
I still have another problem, using the compiled version if I write something in the main window, close the page and open it again the content is still there. 
Using the version I compiled from source it does not happen.

LIME server outputs:
```
FILE GET /demo@lime.com .untitled.xml
GET FILE /exist/rest/lime_test/demo@lime.com/.untitled.xml?_xsl=no
```

The Chrome DevTools show this:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
app.js?_dc=1523633810453:1 Error downloading file /demo@lime.com/.untitled.xml Object
(anonymous) @ app.js?_dc=1523633810453:1
```

The DB components, I used in the two versions are identical. What can I check?

**Comment by obujor** [comment] 2018-04-13 17:33
You have to run `npm install` in `lime/scripts` and in `lime-server` but not in `lime` root.

For the second error issue, is your `lime-server` configured properly in order to use your exist instance? This configuration is in `lime-server/documentsdb/config.json`.
You can also check in DevTools network tab if autosave happens and see its status code.

**Comment by PaoloBolzoniBusiness** [comment] 2018-04-16 08:11
This is my `config.json`, I double check and the eXistDB password is indeed "password" (it is not in production). The host value comes from the docker-compose image names. To be sure I tried to change the password in eXistDB and lime complains in the log with `Error: Eist GET DIR request has status code 401` so I would say that it does connect.

```
{
    "abiword": {
        "path": "/usr/bin/abiword",
        "pathWin": "C:\\Users\\octavian.bujor2\\Programs\\AbiWordStable\\bin\\AbiWord.exe"
    },
    "existIsMainBackend": true,
    "existdb": {
        "auth": "admin:password",
        "baseCollection": "/lime_test",
        "host": "existdb",
        "port": "8080",
        "rest": "/exist/rest"
    },
    "existdbPortal": {},
    "filesystem": {
        "documents": "/LIME/doc"
    },
    "mongodb": {
        "collections": {
            "users": "dev_users"
        },
        "url": "mongodb://mongodb:27017/documentsdb"
    },
    "users": {
        "shared_folders": [
            "/LIME/shared"
        ]
    }
}
```

I checked the DevTools' Network and while typing nothing appears in the log. If I explicitly try to Save via Menu (language it, directory "Shared") then two 204 codes appear, here they are (in curl format):

`curl 'http://localhost:9006/documentsdb/Documents/demo@lime.com/?_dc=1523866096406&page=1&start=0&limit=25' -X OPTIONS -H 'Access-Control-Request-Method: GET' -H 'Origin: http://127.0.0.1' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36' -H 'Accept: */*' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Access-Control-Request-Headers: authorization,x-requested-with' --compressed`

`curl 'http://localhost:9006/documentsdb/Documents/demo@lime.com/it/?_dc=1523866105933&page=1&start=0&limit=25' -X OPTIONS -H 'Access-Control-Request-Method: GET' -H 'Origin: http://127.0.0.1' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36' -H 'Accept: */*' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Access-Control-Request-Headers: authorization,x-requested-with' --compressed`

**Comment by obujor** [comment] 2018-04-16 09:37
I think your eXist configuration is ok.
Requests you put in the comment are GET request and not PUT as save request should be.
Try to do this short test:
- Open LIME
- Create a new document, File menu and New document button (you have to fill the form and press ok)
- erase your console in DevTools Network tab
- write some content in the editor
- click on the Save icon in the editor (it should enabled if you have some content not yet saved) or File menu -> Save
- see the network tab in DevTools you have to see a PUT request to  `http://localhost:9006/documentsdb/Documents/demo@lime.com/.untitled.xml`

I did some tests and I think the issue could be also the version of eXist-db you have installed, updated `lime-server` from github is compatible with eXist-db v3 and newer while the old version of `lime-server` from the `lime-release` folder is compatible with eXist-db v2 and not with eXist-db v3.

**Comment by PaoloBolzoniBusiness** [comment] 2018-04-16 12:23
It does appear, here it is the one appeared after I clicked the Save icon.
```
curl 'http://localhost:9006/documentsdb/Documents/demo@lime.com/.untitled.xml' -X PUT -H 'Authorization: Basic ZGVtb0BsaW1lLmNvbTpkZW1v' -H 'Origin: http://127.0.0.1' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36' -H 'Content-Type: text/plain' -H 'Accept: */*' -H 'Referer: http://127.0.0.1/' -H 'X-Requested-With: XMLHttpRequest' -H 'Connection: keep-alive' -H 'DNT: 1' --data-binary $'<?xml version="1.0" encoding="UTF-8"?>\n<akomaNtoso\n    xmlns="http://docs.oasis-open.org/legaldocml/ns/akn/3.0"\n    xmlns:html="http://www.w3.org/1999/xhtml">\n    <bill>This is a test. I want to see the PUT request. Where did I put that? PUT!PUT IT DOWN!</bill>\n</akomaNtoso>\n' --compressed
```
However, the data is still unsaved. I tried to replace my eXistDB with the version 3.6, but apparently nothing changes.

```
[eXist Version : 3.6.0]
[eXist Build : 201711271542]
```

This similar one actually returns 404
```
curl 'http://localhost:9006/documentsdb/Documentsundefined' -X PUT -H 'Authorization: Basic ZGVtb0BsaW1lLmNvbTpkZW1v' -H 'Origin: http://127.0.0.1' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7' -H 'User-Agent: Mozilla /5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36' -H 'Content-Type: text/plain' -H 'Accept: */*' -H 'Referer: http://127.0.0.1/' -H 'X-Requested-With: XMLHttpRequest' -H 'Connection: keep-alive' -H 'DNT: 1' --da ta-binary $'<?xml version="1.0" encoding="UTF-8"?>\n<akomaNtoso\n    xmlns="http://docs.oasis-open.org/legaldocml/ns/akn/3.0"\n    xmlns:html="http://www.w3.org/1999/xhtml">\n    <null>what the hell</null>\n</akomaNtoso>\n' --compressed
```

However, this file exists in the filesystem:
` /LIME/doc/demo\@lime.com/.untitled.xml`

**Comment by obujor** [comment] 2018-04-16 12:38
Could you check if the file was actually saved in eXist? You have to use the exist db java client.

**Comment by PaoloBolzoniBusiness** [comment] 2018-04-16 12:53
The "open document" section of LIME appears empty, but it is actually there, I am getting more and more confused...
```
root@bd25b504f27e:/opt/exist# ./bin/client.sh -s -u admin -P password
[...]
exist:/db>ls
drwxr-xr-x admin     dba       lime_test
drwxr-xr-x SYSTEM    dba       apps
drwxr-xr-x SYSTEM    dba       system
exist:/db>cd lime_test
exist:/db/lime_test>ls
drwxr-xr-x admin     dba       demo@lime.com
exist:/db/lime_test>cd demo@lime.com
exist:/db/lime_test/demo@lime.com>ls
-rw-r--r--      admin   dba     .untitled.xml   Mon Apr 16 12:26:43 UTC 2018
```

**Comment by obujor** [comment] 2018-04-16 13:09
I expected it to be there.
The problem is not the saving part but the opening one.

In your PUT request I see this content:
`<akomaNtoso 
    xmlns="http://docs.oasis-open.org/legaldocml/ns/akn/3.0" 
    xmlns:html="http://www.w3.org/1999/xhtml">
    <bill>This is a test. I want to see the PUT request. Where did I put that? PUT!PUT IT DOWN!</bill>
</akomaNtoso>`

This is not good because the metadata tag `<meta>` is missing (this is another issue, I have to investigate why it's missing). So when you are opening lime, maybe by reloading the tab, lime sees that metadata is missing so it have to build it from scratch so it opens the "New document" pop up window see the attached screenshot below:
![newdoc](https://user-images.githubusercontent.com/3893568/38810518-47c361ea-4187-11e8-8987-35a7b6ab9081.PNG)

In this case you have two choices:
- close it, this means that you don't want to open that document
- fill in the missing parts and click "Ok" and you will see your file

![testput](https://user-images.githubusercontent.com/3893568/38810681-d2d49d3a-4187-11e8-81b4-2881e784230c.png)

**Comment by PaoloBolzoniBusiness** [comment] 2018-04-16 14:11
I can replicate this behavior.

Since now we apparently are on the same page, I would like to ask can you save and load documents properly?

If I save, I cannot find it in the load menu.

**Comment by obujor** [comment] 2018-04-17 08:04
When a new document is created/imported it will be saved/autosaved in a special file named `.untitled.xml`, you cannot open this file manually the editor opens it automatically when there's no other file opened before. Therefore in your case when you click the save button it just saves the content in this special file. If you want to save it in a folder to be able to open it in the future you have to use the "Save as" button, this will create a copy of your file in a specified position, after doing this when you will have pressed the "Save" button the content will be saved in the new file you chosen before.

This's a simple explanation, there's a more technical one that involves [AkomaNtoso ](http://www.akomantoso.org/) which uses [FRBR](https://en.wikipedia.org/wiki/Functional_Requirements_for_Bibliographic_Records) layering. The "Save" button overwrites the current Expression of the current Work, in other words it just updated the content in the same file. While the "Save as" button can create a new Work or a new Expression of the current Work depending on what folder you chose in the "Save as" window. If you are using the "Metadata editor" there's an exception of this behaviour because you can create a new Expression/Work using the "Save" button. To better understand these concepts I suggest you to read [AkomaNtoso documentation](http://www.akomantoso.org/).

**Comment by obujor** [comment] 2018-04-18 08:06
The original issue was clarified so I'm closing it.

**Closed as completed by obujor** 2018-04-18 08:06 UTC
