### ISSUE TITLE
Unable to create new documents and save

### ISSUE THREAD

**Issue by bourkedo** [cirsfid-unibo/lime#47] opened 2017-10-09 21:36 UTC
Hi folks

I have been successfully using LIME to edit and save documents.  

However, for no immediately obvious reason today it throws an error on creating or opening documents.  I have restarted MongoDB, eXist, and node server.js and apache tomcat my webserver and the whole pc.

The error that is being thrown by node server.js is below;

Any further help to troubleshoot would be greatly appreciated.

Cheers ..... Donal

C:\Users\donal\Downloads\lime-server>node server.js
libxml validation: enabled
libxml XSLT: enabled
Listening on port 9006
Saxon XSLT: enabled
Connected to MongoDb server  mongodb://localhost:27017
DIR GET /donal.bourke@principious.com/
GET DIR /exist/rest/lime_test/donal.bourke%2540principious.com/
filelist []
Error: Eist GET DIR request has status code 401
    at SAXStream.<anonymous> (C:\Users\donal\Downloads\lime-server\documentsdb\utils\backend_exist.js:87:26)
    at emitNone (events.js:86:13)
    at SAXStream.emit (events.js:185:7)
    at Object.SAXStream._parser.onend (C:\Users\donal\Downloads\lime-server\node_modules\sax\lib\sax.js:190:10)
    at emit (C:\Users\donal\Downloads\lime-server\node_modules\sax\lib\sax.js:624:35)
    at end (C:\Users\donal\Downloads\lime-server\node_modules\sax\lib\sax.js:667:5)
    at Object.end (C:\Users\donal\Downloads\lime-server\node_modules\sax\lib\sax.js:154:24)
    at SAXStream.end (C:\Users\donal\Downloads\lime-server\node_modules\sax\lib\sax.js:248:18)    at IncomingMessage.onend (_stream_readable.js:511:10)
    at IncomingMessage.g (events.js:292:16)
Restarting service.
libxml validation: enabled
libxml XSLT: enabled
Listening on port 9006
Saxon XSLT: enabled
Connected to MongoDb server  mongodb://localhost:27017

**Comment by obujor** [comment] 2017-10-10 07:54
Hi Donal,

the error you are getting is directly from eXist rest interface, by looking at the status code it means that the request is Unauthorized. I reproduced the same error by setting the wrong credentials in "lime-server/documentsdb/config.json" at "existDb.auth" field.

I think the problem is the documentsdb configuration of lime-server ( "lime-server/documentsdb/config.json") particulary the "existDb.auth" value but check all "existDb" fields. This configuration must contain your local eXist server configuration. You can also check the credentials by logging in eXist db using the Java Admin Client.

Remember to restart the lime-server after changing of config.json file.

**Comment by bourkedo** [comment] 2017-10-10 08:25
Hi Octavian,

My config.json file is as follows;

Is there a field for password as I don't seem to have one in there;

{
    "mongodb": {
        "url": "mongodb://localhost:27017",
        "collections": {
            "users": "dev_users"
        }
    },
    "filesystem": {
        "documents": "C:/data/documents/"
    },
    "users": {
        "shared_folders": [
            "C:/data/shared/"
        ]
    },
    "existIsMainBackend": true,
    "existdb": {
        "host": "localhost",
        "port": 8080,
        "rest": "/exist/rest",
        "baseCollection": "/lime_test",
        "auth": "admin:exist"
    },
    "existdbPortal": {},
    "abiword": {
        "path": "/usr/bin/abiword",
        "pathWin": "C:\\Users\\octavian.bujor2\\Programs\\AbiWordStable\\bin\\AbiWord.exe"
    }
}

**Comment by obujor** [comment] 2017-10-10 08:48
eXist db rest api uses "HTTPS Basic Authentication", if you want to know more look [here](https://exist-db.org/exist/apps/doc/devguide_rest.xml).
So in the config.json you have basic authentication style config, so the field "existdb.auth" is exist username and password as this "username:password".
In your configuration is set as"auth": "admin:exist", so "admin" is the username and "exist" is the password, you have to change these with your local credentials.

**Comment by bourkedo** [comment] 2017-10-10 09:35
Thanks for that Octavian,

The credentials now appear to be working and I do not get the error;

However, when I try to open a saved file I cannot navigate beyond my email folder in the application as shown in the attached screenshot. See also trace below, I do not get any saved documents showing up in the navigation.  I have restarted all services/servers to no avail.

As always your help greatly appreciated.

![2017-10-10 10_23_34-lime - language independent markup editor]

(https://user-images.githubusercontent.com/32540534/31379332-d5d3ff38-ada5-11e7-91cb-450ad98c8878.png)


C:\Users\donal\Downloads\lime-server>node server.js
libxml validation: enabled
libxml XSLT: enabled
Listening on port 9006
Saxon XSLT: enabled
Connected to MongoDb server  mongodb://localhost:27017
FILE GET /donal.bourke@principious.com/eu/doc/DB/2017-10-10/1/eng@2017-10-10 Operational Risk
GET FILE /exist/rest/lime_test/donal.bourke%2540principious.com/eu/doc/DB/2017-10-10/1/eng%25402017-10-10/Operational%20Risk?_xsl=no
DIR GET /donal.bourke@principious.com/
GET DIR /exist/rest/lime_test/donal.bourke%2540principious.com/
DIR GET /donal.bourke@principious.com/
GET DIR /exist/rest/lime_test/donal.bourke%2540principious.com/

**Comment by obujor** [comment] 2017-10-10 09:47
I can see only the "shared" folder in the screenshot, it seems to be wrongly cropped.

**Comment by bourkedo** [comment] 2017-10-10 10:03
Apologies for that

![2017-10-10 10_23_34-lime - language independent markup editor](https://user-images.githubusercontent.com/32540534/31380884-a4137ef6-adaa-11e7-9836-4a5598887ab2.png)

**Comment by obujor** [comment] 2017-10-10 10:28
Have you tried to click on your folder?

**Comment by bourkedo** [comment] 2017-10-10 10:32
Yes, it does not expand to the right.  See attached screenshot which shows the beginning of the path in the top bar of the dialog box.

![2017-10-10 11_30_15-lime - language independent markup editor](https://user-images.githubusercontent.com/32540534/31382113-80183b64-adae-11e7-8c46-faefae3f95d5.png)

**Comment by bourkedo** [comment] 2017-10-10 10:34
Also the save to this location was successful, as shown below.

![2017-10-10 11_30_15-lime - language independent markup editor](https://user-images.githubusercontent.com/32540534/31382265-faa579aa-adae-11e7-9c10-08a697d4ce6d.png)

**Comment by bourkedo** [comment] 2017-10-10 10:35
Sorry wrong screenshot. Correct one below;

![2017-10-10 11_33_47-lime - language independent markup editor](https://user-images.githubusercontent.com/32540534/31382308-1d3a4a04-adaf-11e7-8f9c-3d5041860044.png)

**Comment by obujor** [comment] 2017-10-10 10:47
Hmm, this is strange, now you can do the last two tests:
- register a new user, save a document and try to open the new folder, it could be that your user is corrupted because of previous credentials problems.
- check the existence of the file in the eXist database, you have to download the Java Admin Client from your local exist url, e.g http://localhost:8080/exist

I hope this will solve the problem, otherwise you can switch to file system as main backend for the storage of files and using exist as backup. You can do this by changing "existIsMainBackend" to false in the config.json file.

**Comment by bourkedo** [comment] 2017-10-10 11:05
I registered a new user and saved;

In exist java client I get the following detail when I navigate to the saved document;

exist:/db/lime_test/donalbourke@hotmail.com/eu/doc/DB/2017-10-10/1/eng@2017-10-10> 

The file is as follows;

<akomaNtoso xmlns="http://docs.oasis-open.org/legaldocml/ns/akn/3.0/WD17" xmlns:html="http://www.w3.org/1999/xhtml">
    <doc name="doc">
        <meta>
            <identification source="#source">
                <FRBRWork>
                    <FRBRthis value="/akn/eu/doc/DB/2017-10-10/1/!main"/>
                    <FRBRuri value="/akn/eu/doc/DB/2017-10-10/1"/>
                    <FRBRdate date="2017-10-10" name=""/>
                    <FRBRauthor href="#" as="#"/>
                    <FRBRcountry value="eu"/>
                </FRBRWork>
                <FRBRExpression>
                    <FRBRthis value="/akn/eu/doc/DB/2017-10-10/1/eng@/!main"/>
                    <FRBRuri value="/akn/eu/doc/DB/2017-10-10/1/eng@"/>
                    <FRBRdate date="2017-10-10" name=""/>
                    <FRBRauthor href="#" as="#"/>
                    <FRBRlanguage language="eng"/>
                </FRBRExpression>
                <FRBRManifestation>
                    <FRBRthis value="/akn/eu/doc/DB/2017-10-10/1/eng@/main.xml/!main"/>
                    <FRBRuri value="/akn/eu/doc/DB/2017-10-10/1/eng@.xml"/>
                    <FRBRdate date="2017-10-10" name=""/>
                    <FRBRauthor href="#" as="#"/>
                </FRBRManifestation>
            </identification>
            <references source="#source">
                <TLCPerson eId="source" href="/akn/ontology/person/somebody" showAs="Somebody"/>
            </references>
        </meta>
        <coverPage eId="coverPage_1">Operational Risk Management Policy</coverPage>
    </doc>
</akomaNtoso>

**Comment by obujor** [comment] 2017-10-10 11:09
Can you open it with LIME now?

**Comment by bourkedo** [comment] 2017-10-10 11:23
No. Still unable to expand donalbourke@hotmail.com

C:\Users\donal\Downloads\lime-server>node server.js
libxml validation: enabled
libxml XSLT: enabled
Listening on port 9006
Saxon XSLT: enabled
Connected to MongoDb server  mongodb://localhost:27017
FILE GET /donalbourke@hotmail.com/eu/doc/DB/2017-10-10/1/eng@2017-10-10 Op Risk Doc
GET FILE /exist/rest/lime_test/donalbourke%2540hotmail.com/eu/doc/DB/2017-10-10/1/eng%25402017-10-10/Op%20Risk%20Doc?_xsl=no
DIR GET /donalbourke@hotmail.com/
![2017-10-10 12_21_10-lime - language independent markup editor](

https://user-images.githubusercontent.com/32540534/31384183-b65d83d0-adb5-11e7-8cd9-287244a4c8e2.png)

**Comment by obujor** [comment] 2017-10-10 11:37
I have to investigate more on this issue because I cannot reproduce it.
In order to do this I need the followings:
- exact version of your lime-server, which release you downloaded?
- eXist db database backup, you can create it from the Java Admin Client 

Thanks

**Comment by bourkedo** [comment] 2017-10-10 11:54
LIME Version: LIME-2.1-build-2017-05-19

[full20171010-1243.zip](https://github.com/cirsfid-unibo/lime/files/1371744/full20171010-1243.zip)

**Comment by obujor** [comment] 2017-10-11 11:21
Ok now I can reproduce this strange behavior. This happens only when eXist-db is executed in Windows.
However lime-server have to handle this, so I'm going to move this issue to https://github.com/cirsfid-unibo/lime-server and it will be fixed soon.

**Comment by obujor** [comment] 2017-10-11 11:21
This issue was moved to cirsfid-unibo/lime-server#2

**Closed as completed by obujor** 2017-10-11 11:21 UTC
